Mahdiyeh/ remove_cryptocurrency_market
binary-com/binary-static pull request #6570
Opened 2021-06-02 06:41 UTC by mahdiyeh-fs

2021-06-03 01:34 UTC, akmal-binary submitted a review, later dismissed

2021-06-04 03:15 UTC, matin-binary requested changes
The reason behind disabling cryptocurrencies is that Crypto only supports Multipliers in contracts_for, it is the same case for Jump indices. Since we don't have Multipliers in platforms other than Deriv-app, we are trying to hide based on the markets, but it is best to filter out based on shortcodes using regex to make sure it will handle other cases and avoid double work in future.
So I suggest using \(?:JD[0-9])|(?:cry_[A-Z])\ to filter out shortcodes. JD for Jump indices and cry for Cryptos.
Feel free to have a look into Zaki's changes in this PR https://redmine.deriv.cloud/issues/30826

2021-06-08 03:19 UTC, matin-binary approved these changes

2021-06-08 03:45 UTC, negarn approved these changes

2021-06-09 10:34 UTC, merged