Ali / trackjs mt5 bugfix
binary-com/binary-static pull request #6623
Opened 2021-06-22 05:45 UTC by ali-fs

2021-06-22 09:53 UTC, akmal-binary submitted a review, later dismissed

2021-06-22 12:21 UTC, mustofa-binary requested changes

2021-06-22 12:21 UTC, mustofa-binary commented on src/javascript/app/pages/user/metatrader/metatrader.ui.js
> +        const trading_servers = State.getResponse('trading_servers') || (await BinarySocket.send({ trading_servers: 1 })).trading_servers;
there would still be a possibility that `trading_servers` is undefined if websocket call has an error, and i think its better to try catch an async call

2021-08-17 07:14 UTC, mustofa-binary approved these changes

2021-09-07 08:23 UTC, merged