Improve automatic translation script
binary-com/binary-static pull request #6654
Opened 2021-07-05 11:36 UTC by ali-fs

2021-07-05 16:45 UTC, mustofa-binary requested changes

2021-07-05 16:45 UTC, mustofa-binary commented on .github/workflows/sync_crowdin_translations.yml
> +      - name: Setup Project and enviroonment
```suggestion
      - name: Setup Project and environment
```

2021-07-06 06:01 UTC, mustofa-binary approved these changes

2021-07-15 11:07 UTC, mustofa-binary submitted a review, later dismissed

2021-07-15 11:11 UTC, reza-fs submitted a review, later dismissed

2021-08-09 05:18 UTC, mustofa-binary approved these changes

2021-08-09 05:18 UTC, merged